--- #YAML:1.0
name:               CGI-Info
version:            0.08
abstract:           Information about the CGI environment
author:
    - Nigel Horne <njh@bandsman.co.uk>
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Cwd:             0
    File::Spec:      0
    Sys::Hostname:   0
    Test::More:      0.82
    URI::Heuristic:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
